import type { ChainConfig } from "@testnet-router/core";
import { CHAIN_IDS, faucetsForChain } from "./faucets";
import { OP_STANDARD_BRIDGES } from "./bridges";
import { SOURCES } from "./sources";

const src = SOURCES.publicRpcProbe;

type ChainSeed = Omit<ChainConfig, "faucets" | "testnet" | "vm" | "source" | "opStack"> & {
  source?: ChainConfig["source"];
};

const seeds: ChainSeed[] = [
  {
    id: CHAIN_IDS.ETHEREUM_SEPOLIA,
    key: "ethereum-sepolia",
    tokenIndexer: { kind: "blockscout", baseUrl: "https://eth-sepolia.blockscout.com" },
    name: "Ethereum Sepolia",
    shortName: "Sepolia",
    tier: 1,
    nativeAsset: {
      canonicalAssetId: "ETH",
      symbol: "ETH",
      name: "Sepolia Ether",
      decimals: 18,
      wrappedAddress: "0xfFf9976782d46CC05630D1f6eBAb18b2324d6B14",
      wrappedSymbol: "WETH",
      wrappedVerified: true,
    },
    rpcUrls: ["https://ethereum-sepolia-rpc.publicnode.com", "https://rpc.sepolia.org", "https://1rpc.io/sepolia"],
    explorerUrl: "https://sepolia.etherscan.io",
    cctpDomain: 0,
    finality: { kind: "probabilistic", confirmations: 2 },
    color: "#627EEA",
  },
  {
    id: CHAIN_IDS.BASE_SEPOLIA,
    key: "base-sepolia",
    tokenIndexer: { kind: "blockscout", baseUrl: "https://base-sepolia.blockscout.com" },
    name: "Base Sepolia",
    shortName: "Base",
    tier: 1,
    nativeAsset: {
      canonicalAssetId: "ETH",
      symbol: "ETH",
      name: "Base Sepolia Ether",
      decimals: 18,
      wrappedAddress: "0x4200000000000000000000000000000000000006",
      wrappedSymbol: "WETH",
      wrappedVerified: true,
    },
    rpcUrls: ["https://sepolia.base.org", "https://base-sepolia-rpc.publicnode.com"],
    explorerUrl: "https://sepolia.basescan.org",
    cctpDomain: 6,
    finality: { kind: "rollup", confirmations: 1 },
    color: "#0052FF",
  },
  {
    id: CHAIN_IDS.OP_SEPOLIA,
    key: "op-sepolia",
    tokenIndexer: { kind: "blockscout", baseUrl: "https://optimism-sepolia.blockscout.com" },
    name: "OP Sepolia",
    shortName: "OP",
    tier: 1,
    nativeAsset: {
      canonicalAssetId: "ETH",
      symbol: "ETH",
      name: "OP Sepolia Ether",
      decimals: 18,
      wrappedAddress: "0x4200000000000000000000000000000000000006",
      wrappedSymbol: "WETH",
      wrappedVerified: true,
    },
    rpcUrls: ["https://sepolia.optimism.io", "https://optimism-sepolia-rpc.publicnode.com"],
    explorerUrl: "https://sepolia-optimism.etherscan.io",
    cctpDomain: 2,
    finality: { kind: "rollup", confirmations: 1 },
    color: "#FF0420",
  },
  {
    id: CHAIN_IDS.ARBITRUM_SEPOLIA,
    key: "arbitrum-sepolia",
    tokenIndexer: { kind: "blockscout", baseUrl: "https://arbitrum-sepolia.blockscout.com" },
    name: "Arbitrum Sepolia",
    shortName: "Arbitrum",
    tier: 1,
    nativeAsset: {
      canonicalAssetId: "ETH",
      symbol: "ETH",
      name: "Arbitrum Sepolia Ether",
      decimals: 18,
      wrappedAddress: "0x980B62Da83eFf3D4576C647993b0c1D7faf17c73",
      wrappedSymbol: "WETH",
      wrappedVerified: true,
    },
    rpcUrls: ["https://sepolia-rollup.arbitrum.io/rpc", "https://arbitrum-sepolia-rpc.publicnode.com"],
    explorerUrl: "https://sepolia.arbiscan.io",
    cctpDomain: 3,
    finality: { kind: "rollup", confirmations: 1 },
    color: "#12AAFF",
  },
  {
    id: CHAIN_IDS.ARC_TESTNET,
    key: "arc-testnet",
    tokenIndexer: { kind: "blockscout", baseUrl: "https://explorer.testnet.arc.io" },
    name: "Arc Testnet",
    shortName: "Arc",
    tier: 1,
    nativeAsset: {
      canonicalAssetId: "USDC",
      symbol: "USDC",
      name: "USDC (Arc native gas)",
      // eth_getBalance returns 18 decimals; ERC-20 interface is 6 decimals.
      decimals: 18,
      erc20Mirror: {
        address: "0x3600000000000000000000000000000000000000",
        decimals: 6,
      },
    },
    rpcUrls: ["https://rpc.testnet.arc.io"],
    explorerUrl: "https://explorer.testnet.arc.io",
    cctpDomain: 26,
    finality: { kind: "deterministic", confirmations: 1 },
    source: SOURCES.arcDocs,
    color: "#2775CA",
  },
  {
    id: CHAIN_IDS.MONAD_TESTNET,
    key: "monad-testnet",
    name: "Monad Testnet",
    shortName: "Monad",
    tier: 1,
    nativeAsset: {
      canonicalAssetId: "MON",
      symbol: "MON",
      name: "Monad",
      decimals: 18,
      // Wrapped MON deployment not verified on-chain at snapshot time: no WRAP edge.
    },
    rpcUrls: ["https://testnet-rpc.monad.xyz"],
    explorerUrl: "https://testnet.monadexplorer.com",
    cctpDomain: 15,
    finality: { kind: "deterministic", confirmations: 1 },
    source: SOURCES.monadDevelopers,
    color: "#836EF9",
  },
  {
    id: CHAIN_IDS.AVALANCHE_FUJI,
    key: "avalanche-fuji",
    name: "Avalanche Fuji",
    shortName: "Fuji",
    tier: 1,
    nativeAsset: {
      canonicalAssetId: "AVAX",
      symbol: "AVAX",
      name: "Avalanche",
      decimals: 18,
      wrappedAddress: "0xd00ae08403B9bbb9124bB305C09058E32C39A48c",
      wrappedSymbol: "WAVAX",
      wrappedVerified: true,
    },
    rpcUrls: ["https://api.avax-test.network/ext/bc/C/rpc", "https://avalanche-fuji-c-chain-rpc.publicnode.com"],
    explorerUrl: "https://testnet.snowtrace.io",
    cctpDomain: 1,
    finality: { kind: "deterministic", confirmations: 1 },
    source: SOURCES.avalancheDocs,
    color: "#E84142",
  },
  {
    id: CHAIN_IDS.POLYGON_AMOY,
    key: "polygon-amoy",
    name: "Polygon Amoy",
    shortName: "Amoy",
    tier: 1,
    nativeAsset: {
      canonicalAssetId: "POL",
      symbol: "POL",
      name: "Polygon Ecosystem Token",
      decimals: 18,
      wrappedAddress: "0x360ad4f9a9A8EFe9A8DCB5f461c4Cc1047E1Dcf9",
      wrappedSymbol: "WPOL",
      wrappedVerified: true,
    },
    rpcUrls: ["https://polygon-amoy-bor-rpc.publicnode.com", "https://rpc-amoy.polygon.technology"],
    explorerUrl: "https://amoy.polygonscan.com",
    cctpDomain: 7,
    finality: { kind: "probabilistic", confirmations: 8 },
    source: SOURCES.polygonRpc,
    color: "#8247E5",
  },
  {
    id: CHAIN_IDS.UNICHAIN_SEPOLIA,
    key: "unichain-sepolia",
    tokenIndexer: { kind: "blockscout", baseUrl: "https://unichain-sepolia.blockscout.com" },
    name: "Unichain Sepolia",
    shortName: "Unichain",
    tier: 1,
    nativeAsset: {
      canonicalAssetId: "ETH",
      symbol: "ETH",
      name: "Unichain Sepolia Ether",
      decimals: 18,
      wrappedAddress: "0x4200000000000000000000000000000000000006",
      wrappedSymbol: "WETH",
      wrappedVerified: true,
    },
    rpcUrls: ["https://sepolia.unichain.org"],
    explorerUrl: "https://sepolia.uniscan.xyz",
    cctpDomain: 10,
    finality: { kind: "rollup", confirmations: 1 },
    color: "#F50DB4",
  },
  {
    id: CHAIN_IDS.WORLD_CHAIN_SEPOLIA,
    key: "world-chain-sepolia",
    tokenIndexer: { kind: "blockscout", baseUrl: "https://worldchain-sepolia.explorer.alchemy.com" },
    name: "World Chain Sepolia",
    shortName: "World",
    tier: 1,
    nativeAsset: {
      canonicalAssetId: "ETH",
      symbol: "ETH",
      name: "World Chain Sepolia Ether",
      decimals: 18,
      wrappedAddress: "0x4200000000000000000000000000000000000006",
      wrappedSymbol: "WETH",
      wrappedVerified: true,
    },
    rpcUrls: ["https://worldchain-sepolia.g.alchemy.com/public", "https://worldchain-sepolia.drpc.org"],
    explorerUrl: "https://worldchain-sepolia.explorer.alchemy.com",
    cctpDomain: 14,
    finality: { kind: "rollup", confirmations: 1 },
    color: "#000000",
  },
  {
    id: CHAIN_IDS.GIWA_SEPOLIA,
    key: "giwa-sepolia",
    tokenIndexer: { kind: "blockscout", baseUrl: "https://sepolia-explorer.giwa.io" },
    name: "GIWA Sepolia",
    shortName: "GIWA",
    tier: 1,
    nativeAsset: {
      canonicalAssetId: "ETH",
      symbol: "ETH",
      name: "GIWA Sepolia Ether",
      decimals: 18,
      wrappedAddress: "0x4200000000000000000000000000000000000006",
      wrappedSymbol: "WETH",
      wrappedVerified: true,
    },
    rpcUrls: ["https://sepolia-rpc.giwa.io"],
    explorerUrl: "https://sepolia-explorer.giwa.io",
    finality: { kind: "rollup", confirmations: 1 },
    source: SOURCES.giwaDocs,
    color: "#1F6FEB",
  },
  {
    id: CHAIN_IDS.LINEA_SEPOLIA,
    key: "linea-sepolia",
    name: "Linea Sepolia",
    shortName: "Linea",
    tier: 2,
    nativeAsset: {
      canonicalAssetId: "ETH",
      symbol: "ETH",
      name: "Linea Sepolia Ether",
      decimals: 18,
      wrappedAddress: "0x10253594A832f967994b44f33411940533302ACb",
      wrappedSymbol: "WETH",
      wrappedVerified: true,
    },
    rpcUrls: ["https://rpc.sepolia.linea.build", "https://linea-sepolia-rpc.publicnode.com"],
    explorerUrl: "https://sepolia.lineascan.build",
    cctpDomain: 11,
    finality: { kind: "rollup", confirmations: 1 },
    source: SOURCES.lineaDocs,
    color: "#61DFFF",
  },
  {
    id: CHAIN_IDS.INK_SEPOLIA,
    key: "ink-sepolia",
    tokenIndexer: { kind: "blockscout", baseUrl: "https://explorer-sepolia.inkonchain.com" },
    name: "Ink Sepolia",
    shortName: "Ink",
    tier: 2,
    nativeAsset: {
      canonicalAssetId: "ETH",
      symbol: "ETH",
      name: "Ink Sepolia Ether",
      decimals: 18,
      wrappedAddress: "0x4200000000000000000000000000000000000006",
      wrappedSymbol: "WETH",
      wrappedVerified: true,
    },
    rpcUrls: ["https://rpc-gel-sepolia.inkonchain.com"],
    explorerUrl: "https://explorer-sepolia.inkonchain.com",
    cctpDomain: 21,
    finality: { kind: "rollup", confirmations: 1 },
    source: SOURCES.inkDocs,
    color: "#7132F5",
  },
  {
    id: CHAIN_IDS.SONIC_TESTNET,
    key: "sonic-testnet",
    name: "Sonic Testnet",
    shortName: "Sonic",
    tier: 2,
    nativeAsset: {
      canonicalAssetId: "S",
      symbol: "S",
      name: "Sonic",
      decimals: 18,
      wrappedAddress: "0x039e2fB66102314Ce7b64Ce5Ce3E5183bc94aD38",
      wrappedSymbol: "wS",
      wrappedVerified: true,
    },
    rpcUrls: ["https://rpc.testnet.soniclabs.com"],
    explorerUrl: "https://explorer.testnet.soniclabs.com",
    cctpDomain: 13,
    finality: { kind: "deterministic", confirmations: 1 },
    source: SOURCES.sonicDocs,
    color: "#F5A623",
  },
  {
    id: CHAIN_IDS.PLUME_TESTNET,
    key: "plume-testnet",
    tokenIndexer: { kind: "blockscout", baseUrl: "https://testnet-explorer.plume.org" },
    name: "Plume Testnet",
    shortName: "Plume",
    tier: 2,
    nativeAsset: {
      canonicalAssetId: "PLUME",
      symbol: "PLUME",
      name: "Plume",
      decimals: 18,
      // Wrapped PLUME not verified on-chain at snapshot time: no WRAP edge.
    },
    rpcUrls: ["https://testnet-rpc.plume.org"],
    explorerUrl: "https://testnet-explorer.plume.org",
    cctpDomain: 22,
    finality: { kind: "rollup", confirmations: 1 },
    source: SOURCES.plumeDocs,
    color: "#F06157",
  },
  {
    id: CHAIN_IDS.SEI_TESTNET,
    key: "sei-testnet",
    name: "Sei Testnet",
    shortName: "Sei",
    tier: 2,
    nativeAsset: {
      canonicalAssetId: "SEI",
      symbol: "SEI",
      name: "Sei",
      decimals: 18,
      wrappedAddress: "0x027D2E627209f1cebA52ADc8A5aFE9318459b44B",
      wrappedSymbol: "WSEI",
      wrappedVerified: true,
    },
    rpcUrls: ["https://evm-rpc-testnet.sei-apis.com"],
    explorerUrl: "https://testnet.seiscan.io",
    cctpDomain: 16,
    finality: { kind: "deterministic", confirmations: 1 },
    source: SOURCES.seiDocs,
    color: "#9E1F19",
  },
  {
    id: CHAIN_IDS.CRONOS_TESTNET,
    key: "cronos-testnet",
    name: "Cronos Testnet",
    shortName: "Cronos",
    tier: 2,
    nativeAsset: {
      canonicalAssetId: "CRO",
      symbol: "TCRO",
      name: "Cronos (test)",
      decimals: 18,
      wrappedAddress: "0x6a3173618859C7cd40fAF6921b5E9eB6A76f1fD4",
      wrappedSymbol: "WCRO",
      wrappedVerified: true,
    },
    rpcUrls: ["https://evm-t3.cronos.org", "https://cronos-testnet.drpc.org"],
    explorerUrl: "https://explorer.cronos.org/testnet",
    cctpDomain: 32,
    finality: { kind: "deterministic", confirmations: 1 },
    source: SOURCES.cronosDocs,
    color: "#002D74",
  },
  {
    id: CHAIN_IDS.PLASMA_TESTNET,
    key: "plasma-testnet",
    name: "Plasma Testnet",
    shortName: "Plasma",
    tier: 2,
    nativeAsset: {
      canonicalAssetId: "XPL",
      symbol: "XPL",
      name: "Plasma",
      decimals: 18,
      // Wrapped XPL not verified on-chain at snapshot time: no WRAP edge.
    },
    rpcUrls: ["https://testnet-rpc.plasma.to"],
    explorerUrl: "https://testnet.plasmascan.to",
    cctpDomain: 33,
    finality: { kind: "deterministic", confirmations: 1 },
    source: SOURCES.plasmaDocs,
    color: "#10B981",
  },
  {
    id: CHAIN_IDS.XLAYER_TESTNET,
    key: "xlayer-testnet",
    name: "X Layer Testnet",
    shortName: "X Layer",
    tier: 2,
    nativeAsset: {
      canonicalAssetId: "OKB",
      symbol: "OKB",
      name: "OKB",
      decimals: 18,
      wrappedAddress: "0x4200000000000000000000000000000000000006",
      wrappedSymbol: "WOKB",
      wrappedVerified: true,
    },
    rpcUrls: ["https://testrpc.xlayer.tech", "https://xlayertestrpc.okx.com"],
    explorerUrl: "https://web3.okx.com/explorer/x-layer-testnet",
    cctpDomain: 37,
    finality: { kind: "rollup", confirmations: 1 },
    source: SOURCES.xlayerDocs,
    color: "#1B1B1B",
  },
  {
    id: CHAIN_IDS.INJECTIVE_TESTNET,
    key: "injective-testnet",
    name: "Injective Testnet",
    shortName: "Injective",
    tier: 2,
    nativeAsset: {
      canonicalAssetId: "INJ",
      symbol: "INJ",
      name: "Injective",
      decimals: 18,
      wrappedAddress: "0x0000000088827d2d103ee2d9A6b781773AE03FfB",
      wrappedSymbol: "WINJ",
      wrappedVerified: true,
    },
    rpcUrls: ["https://k8s.testnet.json-rpc.injective.network", "https://injectiveevm-testnet-rpc.polkachu.com"],
    explorerUrl: "https://testnet.blockscout.injective.network",
    cctpDomain: 29,
    finality: { kind: "deterministic", confirmations: 1 },
    source: SOURCES.injectiveDocs,
    color: "#00F2FE",
  },
];

export const CHAINS: ChainConfig[] = seeds.map((seed) => {
  const op = OP_STANDARD_BRIDGES.find((b) => b.l2ChainId === seed.id);
  return {
    ...seed,
    testnet: true,
    vm: "EVM",
    source: seed.source ?? src,
    faucets: faucetsForChain(seed.id),
    opStack: op
      ? { l1ChainId: op.l1ChainId, l1StandardBridge: op.l1StandardBridge, l2StandardBridge: op.l2StandardBridge }
      : undefined,
  };
});

export const CHAIN_BY_ID: ReadonlyMap<number, ChainConfig> = new Map(CHAINS.map((c) => [c.id, c]));

export function getChain(chainId: number): ChainConfig {
  const c = CHAIN_BY_ID.get(chainId);
  if (!c) throw new Error(`Unknown chain ${chainId}`);
  return c;
}

export function findChain(chainId: number): ChainConfig | undefined {
  return CHAIN_BY_ID.get(chainId);
}

export function chainByKey(key: string): ChainConfig | undefined {
  return CHAINS.find((c) => c.key === key);
}
